/**
 * The case file: a single migration objective being pursued by one applicant
 * under one pathway, plus the sequential phase model that gates its tasks.
 */

import type { IsoDate } from './civil-date.js';
import type { CountryCode } from './jurisdiction.js';

/** The PRD's six-stage journey, as a closed set the workflow engine can order. */
export type MatterPhase =
  | 'intake'
  | 'identity_validation'
  | 'document_assembly'
  | 'submission'
  | 'post_arrival_tracking'
  | 'status_transition';

export const MATTER_PHASE_ORDER: readonly MatterPhase[] = [
  'intake',
  'identity_validation',
  'document_assembly',
  'submission',
  'post_arrival_tracking',
  'status_transition',
];

export function phaseIndex(phase: MatterPhase): number {
  return MATTER_PHASE_ORDER.indexOf(phase);
}

/** True when `a` must complete before `b` can start. */
export function phasePrecedes(a: MatterPhase, b: MatterPhase): boolean {
  return phaseIndex(a) < phaseIndex(b);
}

export type MatterStatus =
  | 'draft'
  | 'active'
  /** Waiting on the applicant. */
  | 'awaiting_applicant'
  /** Waiting on a government body; the clock is outside our control. */
  | 'awaiting_authority'
  /** Waiting on a licensed human to review before anything leaves the platform. */
  | 'awaiting_representative_review'
  | 'submitted'
  | 'granted'
  | 'refused'
  | 'withdrawn'
  | 'abandoned';

/** Statuses in which no further automated work should be scheduled. */
export const TERMINAL_MATTER_STATUSES: readonly MatterStatus[] = [
  'granted',
  'refused',
  'withdrawn',
  'abandoned',
];

export function isTerminal(status: MatterStatus): boolean {
  return TERMINAL_MATTER_STATUSES.includes(status);
}

export interface Applicant {
  readonly id: string;
  /**
   * Every nationality the applicant holds. Order is not significance — see
   * {@link claimedNationality}, which is a separate and legally distinct field.
   */
  readonly nationalities: readonly CountryCode[];
  readonly dateOfBirth?: IsoDate;
}

export interface Matter {
  readonly id: string;
  readonly tenantId: string;
  readonly applicantId: string;
  readonly pathwayId: string;
  readonly targetJurisdiction: CountryCode;
  /**
   * The nationality the applicant actually entered and applied under.
   *
   * This is not a formality. Spain's reduced-residency route is only available
   * to someone who entered and holds residence *as* an Ibero-American national;
   * an Italian-Mexican dual national who entered on the Italian passport cannot
   * later claim the two-year reduction. Storing only `nationalities` and
   * inferring the best one is precisely the bug that costs a client eight years.
   */
  readonly claimedNationality: CountryCode;
  readonly status: MatterStatus;
  readonly phase: MatterPhase;
  readonly openedOn: IsoDate;
  /** Set when a licensed human is accountable for this matter's advice. */
  readonly representativeId: string | null;
  readonly closedOn?: IsoDate;
}

/** A checklist item generated by the rules engine. */
export interface Task {
  readonly id: string;
  readonly matterId: string;
  readonly phase: MatterPhase;
  readonly title: string;
  readonly assignee: TaskAssignee;
  /** Task ids that must be `complete` before this one unlocks. */
  readonly dependsOn: readonly string[];
  readonly status: TaskStatus;
  readonly dueOn?: IsoDate;
  /** Citation ids justifying why this task exists at all. */
  readonly citationIds: readonly string[];
}

export type TaskAssignee = 'applicant' | 'representative' | 'employer' | 'platform' | 'authority';

export type TaskStatus = 'locked' | 'available' | 'in_progress' | 'submitted' | 'complete' | 'waived';

/**
 * Resolve which tasks are unlocked, honouring both explicit dependencies and
 * phase ordering. A task in a later phase stays locked while an earlier phase
 * has incomplete work, which is the PRD's sequential-unlocking requirement.
 */
export function unlockTasks(tasks: readonly Task[], currentPhase: MatterPhase): Task[] {
  const byId = new Map(tasks.map((t) => [t.id, t]));
  const satisfied = (id: string): boolean => {
    const t = byId.get(id);
    return t !== undefined && (t.status === 'complete' || t.status === 'waived');
  };
  return tasks.map((t) => {
    if (t.status !== 'locked') return t;
    const phaseReady = !phasePrecedes(currentPhase, t.phase);
    const depsReady = t.dependsOn.every(satisfied);
    return phaseReady && depsReady ? { ...t, status: 'available' as TaskStatus } : t;
  });
}

/** Detect dependency cycles before they deadlock a matter. Returns the ids involved. */
export function findTaskCycles(tasks: readonly Task[]): string[][] {
  const byId = new Map(tasks.map((t) => [t.id, t]));
  const state = new Map<string, 'visiting' | 'done'>();
  const cycles: string[][] = [];
  const stack: string[] = [];

  const visit = (id: string): void => {
    const s = state.get(id);
    if (s === 'done') return;
    if (s === 'visiting') {
      const from = stack.indexOf(id);
      if (from >= 0) cycles.push(stack.slice(from));
      return;
    }
    const task = byId.get(id);
    if (!task) return;
    state.set(id, 'visiting');
    stack.push(id);
    for (const dep of task.dependsOn) visit(dep);
    stack.pop();
    state.set(id, 'done');
  };

  for (const t of tasks) visit(t.id);
  return cycles;
}
