/**
 * Locale routing.
 *
 * English is unprefixed and Spanish is `/es`. `/matters` is the English matter
 * list; `/es/matters` is the Spanish one. That asymmetry is the whole design —
 * a link sent to a Spanish speaker has to stay Spanish, both variants have to be
 * independently addressable, and neither may acquire a second URL — but Next.js
 * routes on path segments, so it needs a concrete `[locale]` segment to match.
 *
 * This rewrites the unprefixed form onto that segment: `/matters` is served by
 * `app/[locale]/matters` with `locale = 'en'`. A **rewrite**, not a redirect —
 * the address bar keeps showing `/matters`, nothing in the application ever
 * emits `/en/...`, and a reader who bookmarks a page gets the URL they were
 * looking at.
 *
 * ## It also names the locale in a header, and that is load-bearing
 *
 * {@link LOCALE_HEADER} carries the served locale to the **root layout**, which
 * is where `<html lang>` is written and which has no route params to read it
 * from. The alternative — putting `<html>` inside `app/[locale]/layout.tsx` —
 * was tried and abandoned: it works for every page and breaks the one screen
 * nobody screenshots. Next resolves an unmatched URL against the *root* of the
 * tree, so with no root layout a 404 rendered as a bare document with no `lang`,
 * no skip link, no navigation, and an English message for a Spanish reader. A
 * locale system that is correct on seven screens and absent on the eighth is not
 * correct. See `app/layout.tsx` for the one 404 path this still does not reach,
 * and for the evidence that it predates all of this.
 *
 * The header is **set**, never merged, on every request through this middleware,
 * including requests that already carry a locale prefix. A client that sends its
 * own `x-meridian-locale` therefore cannot influence what is served: whatever it
 * sent is replaced before the request reaches the application.
 *
 * ## Two consequences worth stating
 *
 * A literal request for `/en/matters` is rewritten to `/en/en/matters` and
 * routes nowhere, which is correct: English is unprefixed, so `/en` is an
 * ordinary first segment that no page claims. Recognising it would publish every
 * English page under two addresses and make the `hreflang` alternates
 * self-contradictory. `@meridian/i18n`'s `splitLocalePath` takes the same view.
 *
 * `/estimate`, `/españa` and any other path that merely starts with the letters
 * `es` are English, because the prefix match is on a segment boundary. That is
 * not this file's cleverness — it is `splitLocalePath`, which exists precisely
 * so three applications do not each hand-roll `startsWith('/es')` and each get a
 * different edge case wrong.
 *
 * ## What it deliberately does not do
 *
 * It does not read `Accept-Language` and it does not redirect anybody anywhere.
 * A console is bookmarked, pasted into a colleague's chat and cited in a
 * runbook; a header-driven redirect would make the same URL serve two different
 * pages to two people at the same desk, and a reader who then chose English
 * would be sent back to Spanish on the next click. The switcher in the banner is
 * visible on every screen and its target is a real URL. That is the whole
 * mechanism, and it is one a reader can see.
 */

import { NextResponse, type NextRequest } from 'next/server';
import { DEFAULT_LOCALE, splitLocalePath } from '@meridian/i18n';

/**
 * Request header carrying the locale this response is being served in.
 *
 * Internal to this application: it is attached to the rewritten request, never
 * to a response, and never read from what a client sent.
 */
export const LOCALE_HEADER = 'x-meridian-locale';

export function middleware(request: NextRequest): NextResponse {
  const { explicit, locale, path } = splitLocalePath(request.nextUrl.pathname);

  const headers = new Headers(request.headers);
  headers.set(LOCALE_HEADER, locale);

  if (explicit) return NextResponse.next({ request: { headers } });

  const url = request.nextUrl.clone();
  // `path` is already canonicalised — one leading slash, no duplicate or
  // trailing slashes — so the rewritten target cannot pick up an empty segment.
  url.pathname = path === '/' ? `/${DEFAULT_LOCALE}` : `/${DEFAULT_LOCALE}${path}`;
  return NextResponse.rewrite(url, { request: { headers } });
}

export const config = {
  /**
   * Everything except the framework's own assets and the metadata routes.
   *
   * `robots.txt` and `sitemap.xml` are generated by `app/robots.ts` and
   * `app/sitemap.ts`, which sit outside the `[locale]` segment because there is
   * one of each for the host rather than one per language. Rewriting them would
   * send a crawler's request for `/robots.txt` to a page that does not exist.
   */
  matcher: ['/((?!_next/|robots\\.txt|sitemap\\.xml|icon\\.svg|favicon\\.ico).*)'],
};
